In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
data=pd.read_csv('C:/Users/kesav/OneDrive/Desktop/Academics/Data analytics/Assignment/Assignment-2/data.csv')
# with pd.option_context("display.max_columns", None):
#     display(data.head())

In [4]:
def convert_float(x):
    return float(x.replace(',',''))
data['Price_per_unit_area']=data['Price_per_unit_area'].apply(convert_float)

In [5]:
data.loc[((data['Price_per_unit_area']>=100) & (data['Price_per_unit_area']<=10000)), 'Price_per_unit_area'] = 'Luxury'

In [6]:
property=data[((data['City_name']=='Ahmedabad') | (data['City_name']=='Kolkata') | 
           (data['City_name']=='Delhi') | (data['City_name']=='Lucknow')) & 
           (data['Property_status']=='Under Construction') & 
           (data['Price_per_unit_area']=='Luxury')]

In [7]:
threshold=17
for i in data.columns:
    temp=property[i].drop_duplicates()
    if(len(temp)>threshold):
        property.pop(i)
    elif data[i].dtype=='bool':
        property.pop(i)
    elif len(data[i].drop_duplicates())==1 and i!='Price_per_unit_area ':
        property.pop(i)

In [8]:
#Generalization based on no of distinct values
att_thre=5
for i in property.columns:
    if len(property[i].drop_duplicates())>=att_thre:
        if i == "No_of_BHK":
            property['No_of_BHK'] = property['No_of_BHK'].replace(['0 BHK','1 RK','1 BHK','2 RK','2 BHK','3 BHK','3 RK','4 BHK'],'Small house')
            property['No_of_BHK'] = property['No_of_BHK'].replace(['5 BHK','6 BHK','7 BHK','8 BHK','9 BHK'],'Luxury')
            property['No_of_BHK'] = property['No_of_BHK'].replace(['10 BHK','11 BHK','12 BHK','14 BHK'],'Bungalow')
        
        elif i=="Property_type":
            property['Property_type']=property['Property_type'].replace(['Apartment','Residential Plot'],'Shared')
            property['Property_type']=property['Property_type'].replace(['Villa','Independent House','Independent Floor'],'Individual')
        else:
            property.pop(i)

In [9]:
#Droppping the redundant & unwante tuples
property.pop('City_id')
newproperty=property.drop_duplicates()
newproperty=newproperty.drop_duplicates(['City_name','No_of_BHK','is_furnished'],keep='first')

In [10]:
newproperty

,Property_type,Property_status,Price_per_unit_area,Property_building_status,City_name,No_of_BHK,is_furnished
0,Shared,Under Construction,Luxury,ACTIVE,Ahmedabad,Small house,Unfurnished
33,Shared,Under Construction,Luxury,ACTIVE,Ahmedabad,Luxury,Unfurnished
770,Shared,Under Construction,Luxury,ACTIVE,Ahmedabad,Small house,Semi-Furnished
774,Shared,Under Construction,Luxury,ACTIVE,Ahmedabad,Small house,Furnished
3116,Shared,Under Construction,Luxury,ACTIVE,Ahmedabad,Luxury,Semi-Furnished
41229,Individual,Under Construction,Luxury,ACTIVE,Delhi,Small house,Unfurnished
41766,Individual,Under Construction,Luxury,ACTIVE,Delhi,Small house,Semi-Furnished
47002,Individual,Under Construction,Luxury,ACTIVE,Delhi,Small house,Furnished
57642,Shared,Under Construction,Luxury,ACTIVE,Kolkata,Small house,Unfurnished
57656,Individual,Under Construction,Luxury,ACTIVE,Kolkata,Luxury,Unfurnished
58235,Shared,Under Construction,Luxury,ACTIVE,Kolkata,Small house,Semi-Furnished
58519,Shared,Under Construction,Luxury,ACTIVE,Kolkata,Small house,Furnished
64734,Individual,Under Construction,Luxury,ACTIVE,Kolkata,Luxury,Semi-Furnished
69866,Shared,Under Construction,Luxury,ACTIVE,Lucknow,Small house,Unfurnished
69896,Individual,Under Construction,Luxury,ACTIVE,Lucknow,Small house,Furnished
69898,Shared,Under Construction,Luxury,ACTIVE,Lucknow,Small house,Semi-Furnished
69996,Individual,Under Construction,Luxury,ACTIVE,Lucknow,Luxury,Unfurnished
71342,Shared,Under Construction,Luxury,ACTIVE,Lucknow,Luxury,Furnished